const http=require('http'),fs=require('fs'),path=require('path'),https=require('https');
const PORT=Number(process.env.PORT||8787),ROOT=__dirname;
const KEYS={twelve:process.env.TWELVE_DATA_API_KEY||'',finnhub:process.env.FINNHUB_API_KEY||'',alpha:process.env.ALPHA_VANTAGE_API_KEY||''};
const cache=new Map();
function now(){return Date.now()} function cached(k,ttl){const v=cache.get(k);return v&&now()-v.t<ttl?v.v:null} function put(k,v){cache.set(k,{t:now(),v});return v}
function getJson(url,timeout=9000){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'PortfolioPulseAI/4.0'}},r=>{let b='';r.on('data',d=>b+=d);r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)return reject(new Error('HTTP '+r.statusCode));try{resolve(JSON.parse(b))}catch(e){reject(e)}})});req.setTimeout(timeout,()=>req.destroy(new Error('timeout')));req.on('error',reject)})}
async function firstOk(tasks){let last;for(const t of tasks){try{const v=await t();if(v)return v}catch(e){last=e}}throw last||new Error('No provider available')}
function normalizeType(x){x=String(x||'').toLowerCase();if(x.includes('etf')||x.includes('fund'))return'ETF';if(x.includes('crypto'))return'Crypto';if(x.includes('index'))return'Index';return'Equity'}
async function searchTwelve(q){if(!KEYS.twelve)return null;const j=await getJson('https://api.twelvedata.com/symbol_search?symbol='+encodeURIComponent(q)+'&outputsize=12&apikey='+encodeURIComponent(KEYS.twelve));if(!Array.isArray(j.data))throw new Error(j.message||'Twelve search failed');return j.data.map(x=>({symbol:x.symbol,name:x.instrument_name||x.symbol,exchange:x.exchange||'',currency:x.currency||'',asset:normalizeType(x.instrument_type),country:x.country||'',provider:'Twelve Data'}))}
async function searchFinnhub(q){if(!KEYS.finnhub)return null;const j=await getJson('https://finnhub.io/api/v1/search?q='+encodeURIComponent(q)+'&token='+encodeURIComponent(KEYS.finnhub));if(!Array.isArray(j.result))throw new Error('Finnhub search failed');return j.result.slice(0,12).map(x=>({symbol:x.symbol,name:x.description||x.displaySymbol||x.symbol,exchange:'',currency:'',asset:normalizeType(x.type),country:'',provider:'Finnhub'}))}
async function searchAlpha(q){if(!KEYS.alpha)return null;const j=await getJson('https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords='+encodeURIComponent(q)+'&apikey='+encodeURIComponent(KEYS.alpha));const a=j.bestMatches;if(!Array.isArray(a))throw new Error(j.Note||j.Information||'Alpha search failed');return a.slice(0,12).map(x=>({symbol:x['1. symbol'],name:x['2. name'],exchange:x['4. region']||'',currency:x['8. currency']||'',asset:normalizeType(x['3. type']),country:x['4. region']||'',provider:'Alpha Vantage'}))}
async function doSearch(q){const k='s:'+q.toLowerCase(),c=cached(k,3600000);if(c)return c;return put(k,await firstOk([()=>searchTwelve(q),()=>searchFinnhub(q),()=>searchAlpha(q)]))}
async function quoteTwelve(symbol){if(!KEYS.twelve)return null;const j=await getJson('https://api.twelvedata.com/quote?symbol='+encodeURIComponent(symbol)+'&apikey='+encodeURIComponent(KEYS.twelve));if(j.status==='error')throw new Error(j.message);const p=Number(j.close||j.price);if(!isFinite(p))throw new Error('Bad Twelve quote');return{symbol,price:p,previousClose:Number(j.previous_close||0),change:Number(j.change||0),percentChange:Number(j.percent_change||0),currency:j.currency||'',exchange:j.exchange||'',name:j.name||symbol,datetime:j.datetime||new Date().toISOString(),provider:'Twelve Data',status:'LIVE/LATEST'} }
async function quoteFinnhub(symbol){if(!KEYS.finnhub)return null;const j=await getJson('https://finnhub.io/api/v1/quote?symbol='+encodeURIComponent(symbol)+'&token='+encodeURIComponent(KEYS.finnhub));if(!j||!Number(j.c))throw new Error('Bad Finnhub quote');return{symbol,price:Number(j.c),previousClose:Number(j.pc||0),change:Number(j.d||0),percentChange:Number(j.dp||0),currency:'',exchange:'',name:symbol,datetime:j.t?new Date(j.t*1000).toISOString():new Date().toISOString(),provider:'Finnhub',status:'LIVE/LATEST'} }
async function quoteAlpha(symbol){if(!KEYS.alpha)return null;const j=await getJson('https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol='+encodeURIComponent(symbol)+'&apikey='+encodeURIComponent(KEYS.alpha));const q=j['Global Quote'];if(!q||!Number(q['05. price']))throw new Error(j.Note||j.Information||'Bad Alpha quote');return{symbol,price:Number(q['05. price']),previousClose:Number(q['08. previous close']||0),change:Number(q['09. change']||0),percentChange:Number(String(q['10. change percent']||'0').replace('%','')),currency:'',exchange:'',name:symbol,datetime:q['07. latest trading day']||new Date().toISOString(),provider:'Alpha Vantage',status:'LATEST/PLAN-DEPENDENT'} }
async function doQuote(symbol){const k='q:'+symbol,c=cached(k,20000);if(c)return c;return put(k,await firstOk([()=>quoteTwelve(symbol),()=>quoteFinnhub(symbol),()=>quoteAlpha(symbol)]))}
function intervalFor(range){if(range==='1D')return{interval:'5min',outputsize:90};if(range==='1W')return{interval:'1h',outputsize:80};return{interval:'1day',outputsize:range==='1M'?40:range==='3M'?100:range==='YTD'?280:range==='1Y'?370:range==='5Y'?1400:5000}}
async function histTwelve(symbol,range){if(!KEYS.twelve)return null;const p=intervalFor(range);const j=await getJson('https://api.twelvedata.com/time_series?symbol='+encodeURIComponent(symbol)+'&interval='+p.interval+'&outputsize='+p.outputsize+'&order=asc&apikey='+encodeURIComponent(KEYS.twelve));if(!Array.isArray(j.values))throw new Error(j.message||'Twelve history failed');return{symbol,range,provider:'Twelve Data',status:'LIVE/HISTORICAL',points:j.values.map(x=>({t:x.datetime,c:Number(x.close)})).filter(x=>isFinite(x.c))}}
async function histAlpha(symbol,range){if(!KEYS.alpha)return null;if(range==='1D'||range==='1W')return null;const full=(range==='5Y'||range==='ALL');const j=await getJson('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol='+encodeURIComponent(symbol)+'&outputsize='+(full?'full':'compact')+'&apikey='+encodeURIComponent(KEYS.alpha));const ts=j['Time Series (Daily)'];if(!ts)throw new Error(j.Note||j.Information||'Alpha history failed');let pts=Object.keys(ts).sort().map(d=>({t:d,c:Number(ts[d]['4. close'])}));const cutoff=Date.now()-({ '1M':35,'3M':100,'YTD':380,'1Y':380,'5Y':1900,'ALL':20000}[range]||380)*86400000;pts=pts.filter(x=>new Date(x.t).getTime()>=cutoff);return{symbol,range,provider:'Alpha Vantage',status:'HISTORICAL',points:pts}}
async function doHistory(symbol,range){const k='h:'+symbol+':'+range,c=cached(k,range==='1D'?60000:3600000);if(c)return c;return put(k,await firstOk([()=>histTwelve(symbol,range),()=>histAlpha(symbol,range)]))}
function send(res,code,obj){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(obj))}
function serve(req,res){let u=new URL(req.url,'http://x');if(u.pathname==='/api/health')return send(res,200,{ok:true,providers:{twelve:!!KEYS.twelve,finnhub:!!KEYS.finnhub,alpha:!!KEYS.alpha}});
if(u.pathname==='/api/search')return doSearch((u.searchParams.get('q')||'').trim()).then(x=>send(res,200,{ok:true,items:x})).catch(e=>send(res,503,{ok:false,error:e.message}));
if(u.pathname==='/api/quote')return doQuote((u.searchParams.get('symbol')||'').trim()).then(x=>send(res,200,{ok:true,quote:x})).catch(e=>send(res,503,{ok:false,error:e.message}));
if(u.pathname==='/api/history')return doHistory((u.searchParams.get('symbol')||'').trim(),u.searchParams.get('range')||'1Y').then(x=>send(res,200,{ok:true,history:x})).catch(e=>send(res,503,{ok:false,error:e.message}));
let p=u.pathname==='/'?'/index.html':u.pathname; p=path.normalize(p).replace(/^([.][.][/\\])+/, ''); const f=path.join(ROOT,p); if(!f.startsWith(ROOT))return res.writeHead(403).end();fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(f);const ct={'.html':'text/html; charset=utf-8','.js':'application/javascript','.json':'application/json','.css':'text/css'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct,'Cache-Control':ext==='.html'?'no-store':'public, max-age=300'});res.end(b)})}
http.createServer(serve).listen(PORT,'0.0.0.0',()=>console.log('Portfolio Pulse AI v4 on http://localhost:'+PORT));
